parameters:
   user.provider.class: App\SharingBundle\User\Provider
   authentication.handler.class: App\SharingBundle\User\Handler

services:
    user.provider:
       class: %user.provider.class%

    authentication.handler:
        class: %authentication.handler.class%
        tags:
            - { name: 'monolog.logger', channel: 'security' }
