parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     sharing
    database_user:     root
    database_password: wesley

    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       w.v.mendes.s
    mailer_password:   30314557hopi

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
